name: Build on Push

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies(OpenCC)
      run: |
        pip install OpenCC
    - name: Run Script
      run: |
        python ./rime-symbols-gen
    - uses: actions/upload-artifact@v4
      with:
        name: last-build
        path: symbol**
